// Code generated by gencatalog; DO NOT EDIT.
package native

func Abs(value float64) float64                                                            { return 0 }
func Add(values ...float64) float64                                                        { return 0 }
func AddLifeScheduled(value float64, time float64)                                         {}
func Arccos(value float64) float64                                                         { return 0 }
func Arcsin(value float64) float64                                                         { return 0 }
func Arctan(value float64) float64                                                         { return 0 }
func Arctan2(y float64, x float64) float64                                                 { return 0 }
func BeatToBPM(beat float64) float64                                                       { return 0 }
func BeatToStartingBeat(beat float64) float64                                              { return 0 }
func BeatToStartingTime(beat float64) float64                                              { return 0 }
func BeatToTime(beat float64) float64                                                      { return 0 }
func Ceil(value float64) float64                                                           { return 0 }
func Clamp(x float64, a float64, b float64) float64                                        { return 0 }
func Copy(srcId float64, srcIndex float64, dstId float64, dstIndex float64, count float64) {}
func Cos(value float64) float64                                                            { return 0 }
func Cosh(value float64) float64                                                           { return 0 }
func DebugLog(value float64)                                                               {}
func DebugPause()                                                                          {}
func DecrementPost(id float64, index float64) float64                                      { return 0 }
func DecrementPostPointed(id float64, index float64, offset float64) float64               { return 0 }
func DecrementPostShifted(id float64, x float64, y float64, s float64) float64             { return 0 }
func DecrementPre(id float64, index float64) float64                                       { return 0 }
func DecrementPrePointed(id float64, index float64, offset float64) float64                { return 0 }
func DecrementPreShifted(id float64, x float64, y float64, s float64) float64              { return 0 }
func Degree(value float64) float64                                                         { return 0 }
func DestroyParticleEffect(particleId float64)                                             {}
func Divide(values ...float64) float64                                                     { return 0 }
func Draw(id float64, x1 float64, y1 float64, x2 float64, y2 float64, x3 float64, y3 float64, x4 float64, y4 float64, z1 float64, a float64, z2 float64, z3 float64, z4 float64) {
}
func DrawCurvedB(id float64, x1 float64, y1 float64, x2 float64, y2 float64, x3 float64, y3 float64, x4 float64, y4 float64, z1 float64, a float64, n float64, p float64, q float64, z2 float64, z3 float64, z4 float64) {
}
func DrawCurvedBT(id float64, x1 float64, y1 float64, x2 float64, y2 float64, x3 float64, y3 float64, x4 float64, y4 float64, z1 float64, a float64, n float64, p1 float64, q1 float64, p2 float64, q2 float64, z2 float64, z3 float64, z4 float64) {
}
func DrawCurvedL(id float64, x1 float64, y1 float64, x2 float64, y2 float64, x3 float64, y3 float64, x4 float64, y4 float64, z1 float64, a float64, n float64, p float64, q float64, z2 float64, z3 float64, z4 float64) {
}
func DrawCurvedLR(id float64, x1 float64, y1 float64, x2 float64, y2 float64, x3 float64, y3 float64, x4 float64, y4 float64, z1 float64, a float64, n float64, p1 float64, q1 float64, p2 float64, q2 float64, z2 float64, z3 float64, z4 float64) {
}
func DrawCurvedR(id float64, x1 float64, y1 float64, x2 float64, y2 float64, x3 float64, y3 float64, x4 float64, y4 float64, z1 float64, a float64, n float64, p float64, q float64, z2 float64, z3 float64, z4 float64) {
}
func DrawCurvedT(id float64, x1 float64, y1 float64, x2 float64, y2 float64, x3 float64, y3 float64, x4 float64, y4 float64, z1 float64, a float64, n float64, p float64, q float64, z2 float64, z3 float64, z4 float64) {
}
func EaseInBack(value float64) float64                                         { return 0 }
func EaseInCirc(value float64) float64                                         { return 0 }
func EaseInCubic(value float64) float64                                        { return 0 }
func EaseInElastic(value float64) float64                                      { return 0 }
func EaseInExpo(value float64) float64                                         { return 0 }
func EaseInOutBack(value float64) float64                                      { return 0 }
func EaseInOutCirc(value float64) float64                                      { return 0 }
func EaseInOutCubic(value float64) float64                                     { return 0 }
func EaseInOutElastic(value float64) float64                                   { return 0 }
func EaseInOutExpo(value float64) float64                                      { return 0 }
func EaseInOutQuad(value float64) float64                                      { return 0 }
func EaseInOutQuart(value float64) float64                                     { return 0 }
func EaseInOutQuint(value float64) float64                                     { return 0 }
func EaseInOutSine(value float64) float64                                      { return 0 }
func EaseInQuad(value float64) float64                                         { return 0 }
func EaseInQuart(value float64) float64                                        { return 0 }
func EaseInQuint(value float64) float64                                        { return 0 }
func EaseInSine(value float64) float64                                         { return 0 }
func EaseOutBack(value float64) float64                                        { return 0 }
func EaseOutCirc(value float64) float64                                        { return 0 }
func EaseOutCubic(value float64) float64                                       { return 0 }
func EaseOutElastic(value float64) float64                                     { return 0 }
func EaseOutExpo(value float64) float64                                        { return 0 }
func EaseOutInBack(value float64) float64                                      { return 0 }
func EaseOutInCirc(value float64) float64                                      { return 0 }
func EaseOutInCubic(value float64) float64                                     { return 0 }
func EaseOutInElastic(value float64) float64                                   { return 0 }
func EaseOutInExpo(value float64) float64                                      { return 0 }
func EaseOutInQuad(value float64) float64                                      { return 0 }
func EaseOutInQuart(value float64) float64                                     { return 0 }
func EaseOutInQuint(value float64) float64                                     { return 0 }
func EaseOutInSine(value float64) float64                                      { return 0 }
func EaseOutQuad(value float64) float64                                        { return 0 }
func EaseOutQuart(value float64) float64                                       { return 0 }
func EaseOutQuint(value float64) float64                                       { return 0 }
func EaseOutSine(value float64) float64                                        { return 0 }
func Equal(lhs float64, rhs float64) float64                                   { return 0 }
func ExportValue(index float64, value float64)                                 {}
func Floor(value float64) float64                                              { return 0 }
func Frac(value float64) float64                                               { return 0 }
func Get(id float64, index float64) float64                                    { return 0 }
func GetPointed(id float64, index float64, offset float64) float64             { return 0 }
func GetShifted(id float64, x float64, y float64, s float64) float64           { return 0 }
func Greater(lhs float64, rhs float64) float64                                 { return 0 }
func GreaterOr(lhs float64, rhs float64) float64                               { return 0 }
func HasEffectClip(id float64) bool                                            { return false }
func HasParticleEffect(id float64) bool                                        { return false }
func HasSkinSprite(id float64) bool                                            { return false }
func IncrementPost(id float64, index float64) float64                          { return 0 }
func IncrementPostPointed(id float64, index float64, offset float64) float64   { return 0 }
func IncrementPostShifted(id float64, x float64, y float64, s float64) float64 { return 0 }
func IncrementPre(id float64, index float64) float64                           { return 0 }
func IncrementPrePointed(id float64, index float64, offset float64) float64    { return 0 }
func IncrementPreShifted(id float64, x float64, y float64, s float64) float64  { return 0 }
func Judge(source float64, target float64, minPerfect float64, maxPerfect float64, minGreat float64, maxGreat float64, minGood float64, maxGood float64) float64 {
	return 0
}
func JudgeSimple(source float64, target float64, maxPerfect float64, maxGreat float64, maxGood float64) float64 {
	return 0
}
func Lerp(x float64, y float64, s float64) float64        { return 0 }
func LerpClamped(x float64, y float64, s float64) float64 { return 0 }
func Less(lhs float64, rhs float64) float64               { return 0 }
func LessOr(lhs float64, rhs float64) float64             { return 0 }
func Log(value float64) float64                           { return 0 }
func Max(x float64, y float64) float64                    { return 0 }
func Min(x float64, y float64) float64                    { return 0 }
func Mod(values ...float64) float64                       { return 0 }
func MoveParticleEffect(particleId float64, x1 float64, y1 float64, x2 float64, y2 float64, x3 float64, y3 float64, x4 float64, y4 float64) {
}
func Multiply(values ...float64) float64                                                           { return 0 }
func Negate(value float64) float64                                                                 { return 0 }
func Not(value float64) float64                                                                    { return 0 }
func NotEqual(lhs float64, rhs float64) float64                                                    { return 0 }
func Paint(id float64, x float64, y float64, size float64, rotation float64, z float64, a float64) {}
func Play(id float64, distance float64)                                                            {}
func PlayLooped(id float64) float64                                                                { return 0 }
func PlayLoopedScheduled(id float64, startTime float64) float64                                    { return 0 }
func PlayScheduled(id float64, time float64, distance float64)                                     {}
func Power(values ...float64) float64                                                              { return 0 }
func Print(value float64, format float64, decimalPlaces float64, anchorX float64, anchorY float64, pivotX float64, pivotY float64, width float64, height float64, rotation float64, color float64, alpha float64, horizontalAlign float64, background bool) {
}
func Radian(value float64) float64                                                          { return 0 }
func Random(min float64, max float64) float64                                               { return 0 }
func RandomInteger(min float64, max float64) float64                                        { return 0 }
func Rem(values ...float64) float64                                                         { return 0 }
func Remap(a float64, b float64, c float64, d float64, x float64) float64                   { return 0 }
func RemapClamped(a float64, b float64, c float64, d float64, x float64) float64            { return 0 }
func Round(value float64) float64                                                           { return 0 }
func Set(id float64, index float64, value float64) float64                                  { return 0 }
func SetAdd(id float64, index float64, value float64) float64                               { return 0 }
func SetAddPointed(id float64, index float64, offset float64, value float64) float64        { return 0 }
func SetAddShifted(id float64, x float64, y float64, s float64, value float64) float64      { return 0 }
func SetDivide(id float64, index float64, value float64) float64                            { return 0 }
func SetDividePointed(id float64, index float64, offset float64, value float64) float64     { return 0 }
func SetDivideShifted(id float64, x float64, y float64, s float64, value float64) float64   { return 0 }
func SetMod(id float64, index float64, value float64) float64                               { return 0 }
func SetModPointed(id float64, index float64, offset float64, value float64) float64        { return 0 }
func SetModShifted(id float64, x float64, y float64, s float64, value float64) float64      { return 0 }
func SetMultiply(id float64, index float64, value float64) float64                          { return 0 }
func SetMultiplyPointed(id float64, index float64, offset float64, value float64) float64   { return 0 }
func SetMultiplyShifted(id float64, x float64, y float64, s float64, value float64) float64 { return 0 }
func SetPointed(id float64, index float64, offset float64, value float64) float64           { return 0 }
func SetPower(id float64, index float64, value float64) float64                             { return 0 }
func SetPowerPointed(id float64, index float64, offset float64, value float64) float64      { return 0 }
func SetPowerShifted(id float64, x float64, y float64, s float64, value float64) float64    { return 0 }
func SetRem(id float64, index float64, value float64) float64                               { return 0 }
func SetRemPointed(id float64, index float64, offset float64, value float64) float64        { return 0 }
func SetRemShifted(id float64, x float64, y float64, s float64, value float64) float64      { return 0 }
func SetShifted(id float64, x float64, y float64, s float64, value float64) float64         { return 0 }
func SetSubtract(id float64, index float64, value float64) float64                          { return 0 }
func SetSubtractPointed(id float64, index float64, offset float64, value float64) float64   { return 0 }
func SetSubtractShifted(id float64, x float64, y float64, s float64, value float64) float64 { return 0 }
func Sign(value float64) float64                                                            { return 0 }
func Sin(value float64) float64                                                             { return 0 }
func Sinh(value float64) float64                                                            { return 0 }
func Spawn(id float64, memory ...float64)                                                   {}
func SpawnParticleEffect(id float64, x1 float64, y1 float64, x2 float64, y2 float64, x3 float64, y3 float64, x4 float64, y4 float64, duration float64, isLooped bool) float64 {
	return 0
}
func StackEnter(size float64)                               {}
func StackGet(offset float64) float64                       { return 0 }
func StackGetFrame(offset float64) float64                  { return 0 }
func StackGetFramePointer() float64                         { return 0 }
func StackGetPointer() float64                              { return 0 }
func StackGrow(size float64) float64                        { return 0 }
func StackInit()                                            {}
func StackLeave()                                           {}
func StackPop() float64                                     { return 0 }
func StackPush(value float64) float64                       { return 0 }
func StackSet(offset float64, value float64) float64        { return 0 }
func StackSetFrame(offset float64, value float64) float64   { return 0 }
func StackSetFramePointer(value float64) float64            { return 0 }
func StackSetPointer(value float64) float64                 { return 0 }
func StopLooped(loopId float64)                             {}
func StopLoopedScheduled(loopId float64, endTime float64)   {}
func StreamGetNextKey(id float64, key float64) float64      { return 0 }
func StreamGetPreviousKey(id float64, key float64) float64  { return 0 }
func StreamGetValue(id float64, key float64) float64        { return 0 }
func StreamHas(id float64, key float64) bool                { return false }
func StreamSet(id float64, key float64, value float64)      {}
func Tan(value float64) float64                             { return 0 }
func Tanh(value float64) float64                            { return 0 }
func TimeToScaledTime(time float64) float64                 { return 0 }
func TimeToStartingScaledTime(time float64) float64         { return 0 }
func TimeToStartingTime(time float64) float64               { return 0 }
func TimeToTimeScale(time float64) float64                  { return 0 }
func Trunc(value float64) float64                           { return 0 }
func Unlerp(a float64, b float64, x float64) float64        { return 0 }
func UnlerpClamped(a float64, b float64, x float64) float64 { return 0 }
