// Code generated by gencatalog; DO NOT EDIT.
package main

import (
	"github.com/WindowsSov8forUs/sonolus-go/v2/sonolus/native"
	"github.com/WindowsSov8forUs/sonolus-go/v2/sonolus/play"
)

type NativeCoverage struct {
	play.Archetype `archetype:"name=NativeCoverage"`
}

func (*NativeCoverage) Preprocess() {
	result0 := native.Abs(0)
	_ = result0
	result1 := native.Add(0)
	_ = result1
	native.AddLifeScheduled(0, 0)
	result2 := native.Arccos(0)
	_ = result2
	result3 := native.Arcsin(0)
	_ = result3
	result4 := native.Arctan(0)
	_ = result4
	result5 := native.Arctan2(0, 0)
	_ = result5
	result6 := native.BeatToBPM(0)
	_ = result6
	result7 := native.BeatToStartingBeat(0)
	_ = result7
	result8 := native.BeatToStartingTime(0)
	_ = result8
	result9 := native.BeatToTime(0)
	_ = result9
	result10 := native.Ceil(0)
	_ = result10
	result11 := native.Clamp(0, 0, 0)
	_ = result11
	native.Copy(0, 0, 0, 0, 0)
	result12 := native.Cos(0)
	_ = result12
	result13 := native.Cosh(0)
	_ = result13
	native.DebugLog(0)
	native.DebugPause()
	result14 := native.DecrementPost(0, 0)
	_ = result14
	result15 := native.DecrementPostPointed(0, 0, 0)
	_ = result15
	result16 := native.DecrementPostShifted(0, 0, 0, 0)
	_ = result16
	result17 := native.DecrementPre(0, 0)
	_ = result17
	result18 := native.DecrementPrePointed(0, 0, 0)
	_ = result18
	result19 := native.DecrementPreShifted(0, 0, 0, 0)
	_ = result19
	result20 := native.Degree(0)
	_ = result20
	native.DestroyParticleEffect(0)
	result21 := native.Divide(0)
	_ = result21
	native.Draw(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	native.DrawCurvedB(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	native.DrawCurvedBT(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	native.DrawCurvedL(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	native.DrawCurvedLR(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	native.DrawCurvedR(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	native.DrawCurvedT(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	result22 := native.EaseInBack(0)
	_ = result22
	result23 := native.EaseInCirc(0)
	_ = result23
	result24 := native.EaseInCubic(0)
	_ = result24
	result25 := native.EaseInElastic(0)
	_ = result25
	result26 := native.EaseInExpo(0)
	_ = result26
	result27 := native.EaseInOutBack(0)
	_ = result27
	result28 := native.EaseInOutCirc(0)
	_ = result28
	result29 := native.EaseInOutCubic(0)
	_ = result29
	result30 := native.EaseInOutElastic(0)
	_ = result30
	result31 := native.EaseInOutExpo(0)
	_ = result31
	result32 := native.EaseInOutQuad(0)
	_ = result32
	result33 := native.EaseInOutQuart(0)
	_ = result33
	result34 := native.EaseInOutQuint(0)
	_ = result34
	result35 := native.EaseInOutSine(0)
	_ = result35
	result36 := native.EaseInQuad(0)
	_ = result36
	result37 := native.EaseInQuart(0)
	_ = result37
	result38 := native.EaseInQuint(0)
	_ = result38
	result39 := native.EaseInSine(0)
	_ = result39
	result40 := native.EaseOutBack(0)
	_ = result40
	result41 := native.EaseOutCirc(0)
	_ = result41
	result42 := native.EaseOutCubic(0)
	_ = result42
	result43 := native.EaseOutElastic(0)
	_ = result43
	result44 := native.EaseOutExpo(0)
	_ = result44
	result45 := native.EaseOutInBack(0)
	_ = result45
	result46 := native.EaseOutInCirc(0)
	_ = result46
	result47 := native.EaseOutInCubic(0)
	_ = result47
	result48 := native.EaseOutInElastic(0)
	_ = result48
	result49 := native.EaseOutInExpo(0)
	_ = result49
	result50 := native.EaseOutInQuad(0)
	_ = result50
	result51 := native.EaseOutInQuart(0)
	_ = result51
	result52 := native.EaseOutInQuint(0)
	_ = result52
	result53 := native.EaseOutInSine(0)
	_ = result53
	result54 := native.EaseOutQuad(0)
	_ = result54
	result55 := native.EaseOutQuart(0)
	_ = result55
	result56 := native.EaseOutQuint(0)
	_ = result56
	result57 := native.EaseOutSine(0)
	_ = result57
	result58 := native.Equal(0, 0)
	_ = result58
	native.ExportValue(0, 0)
	result59 := native.Floor(0)
	_ = result59
	result60 := native.Frac(0)
	_ = result60
	result61 := native.Get(0, 0)
	_ = result61
	result62 := native.GetPointed(0, 0, 0)
	_ = result62
	result63 := native.GetShifted(0, 0, 0, 0)
	_ = result63
	result64 := native.Greater(0, 0)
	_ = result64
	result65 := native.GreaterOr(0, 0)
	_ = result65
	result66 := native.HasEffectClip(0)
	_ = result66
	result67 := native.HasParticleEffect(0)
	_ = result67
	result68 := native.HasSkinSprite(0)
	_ = result68
	result69 := native.IncrementPost(0, 0)
	_ = result69
	result70 := native.IncrementPostPointed(0, 0, 0)
	_ = result70
	result71 := native.IncrementPostShifted(0, 0, 0, 0)
	_ = result71
	result72 := native.IncrementPre(0, 0)
	_ = result72
	result73 := native.IncrementPrePointed(0, 0, 0)
	_ = result73
	result74 := native.IncrementPreShifted(0, 0, 0, 0)
	_ = result74
	result75 := native.Judge(0, 0, 0, 0, 0, 0, 0, 0)
	_ = result75
	result76 := native.JudgeSimple(0, 0, 0, 0, 0)
	_ = result76
	result77 := native.Lerp(0, 0, 0)
	_ = result77
	result78 := native.LerpClamped(0, 0, 0)
	_ = result78
	result79 := native.Less(0, 0)
	_ = result79
	result80 := native.LessOr(0, 0)
	_ = result80
	result81 := native.Log(0)
	_ = result81
	result82 := native.Max(0, 0)
	_ = result82
	result83 := native.Min(0, 0)
	_ = result83
	result84 := native.Mod(0)
	_ = result84
	native.MoveParticleEffect(0, 0, 0, 0, 0, 0, 0, 0, 0)
	result85 := native.Multiply(0)
	_ = result85
	result86 := native.Negate(0)
	_ = result86
	result87 := native.Not(0)
	_ = result87
	result88 := native.NotEqual(0, 0)
	_ = result88
	native.Paint(0, 0, 0, 0, 0, 0, 0)
	native.Play(0, 0)
	result89 := native.PlayLooped(0)
	_ = result89
	result90 := native.PlayLoopedScheduled(0, 0)
	_ = result90
	native.PlayScheduled(0, 0, 0)
	result91 := native.Power(0)
	_ = result91
	native.Print(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, false)
	result92 := native.Radian(0)
	_ = result92
	result93 := native.Random(0, 0)
	_ = result93
	result94 := native.RandomInteger(0, 0)
	_ = result94
	result95 := native.Rem(0)
	_ = result95
	result96 := native.Remap(0, 0, 0, 0, 0)
	_ = result96
	result97 := native.RemapClamped(0, 0, 0, 0, 0)
	_ = result97
	result98 := native.Round(0)
	_ = result98
	result99 := native.Set(0, 0, 0)
	_ = result99
	result100 := native.SetAdd(0, 0, 0)
	_ = result100
	result101 := native.SetAddPointed(0, 0, 0, 0)
	_ = result101
	result102 := native.SetAddShifted(0, 0, 0, 0, 0)
	_ = result102
	result103 := native.SetDivide(0, 0, 0)
	_ = result103
	result104 := native.SetDividePointed(0, 0, 0, 0)
	_ = result104
	result105 := native.SetDivideShifted(0, 0, 0, 0, 0)
	_ = result105
	result106 := native.SetMod(0, 0, 0)
	_ = result106
	result107 := native.SetModPointed(0, 0, 0, 0)
	_ = result107
	result108 := native.SetModShifted(0, 0, 0, 0, 0)
	_ = result108
	result109 := native.SetMultiply(0, 0, 0)
	_ = result109
	result110 := native.SetMultiplyPointed(0, 0, 0, 0)
	_ = result110
	result111 := native.SetMultiplyShifted(0, 0, 0, 0, 0)
	_ = result111
	result112 := native.SetPointed(0, 0, 0, 0)
	_ = result112
	result113 := native.SetPower(0, 0, 0)
	_ = result113
	result114 := native.SetPowerPointed(0, 0, 0, 0)
	_ = result114
	result115 := native.SetPowerShifted(0, 0, 0, 0, 0)
	_ = result115
	result116 := native.SetRem(0, 0, 0)
	_ = result116
	result117 := native.SetRemPointed(0, 0, 0, 0)
	_ = result117
	result118 := native.SetRemShifted(0, 0, 0, 0, 0)
	_ = result118
	result119 := native.SetShifted(0, 0, 0, 0, 0)
	_ = result119
	result120 := native.SetSubtract(0, 0, 0)
	_ = result120
	result121 := native.SetSubtractPointed(0, 0, 0, 0)
	_ = result121
	result122 := native.SetSubtractShifted(0, 0, 0, 0, 0)
	_ = result122
	result123 := native.Sign(0)
	_ = result123
	result124 := native.Sin(0)
	_ = result124
	result125 := native.Sinh(0)
	_ = result125
	native.Spawn(0, 0)
	result126 := native.SpawnParticleEffect(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, false)
	_ = result126
	native.StackEnter(0)
	result127 := native.StackGet(0)
	_ = result127
	result128 := native.StackGetFrame(0)
	_ = result128
	result129 := native.StackGetFramePointer()
	_ = result129
	result130 := native.StackGetPointer()
	_ = result130
	result131 := native.StackGrow(0)
	_ = result131
	native.StackInit()
	native.StackLeave()
	result132 := native.StackPop()
	_ = result132
	result133 := native.StackPush(0)
	_ = result133
	result134 := native.StackSet(0, 0)
	_ = result134
	result135 := native.StackSetFrame(0, 0)
	_ = result135
	result136 := native.StackSetFramePointer(0)
	_ = result136
	result137 := native.StackSetPointer(0)
	_ = result137
	native.StopLooped(0)
	native.StopLoopedScheduled(0, 0)
	result138 := native.StreamGetNextKey(0, 0)
	_ = result138
	result139 := native.StreamGetPreviousKey(0, 0)
	_ = result139
	result140 := native.StreamGetValue(0, 0)
	_ = result140
	result141 := native.StreamHas(0, 0)
	_ = result141
	native.StreamSet(0, 0, 0)
	result142 := native.Tan(0)
	_ = result142
	result143 := native.Tanh(0)
	_ = result143
	result144 := native.TimeToScaledTime(0)
	_ = result144
	result145 := native.TimeToStartingScaledTime(0)
	_ = result145
	result146 := native.TimeToStartingTime(0)
	_ = result146
	result147 := native.TimeToTimeScale(0)
	_ = result147
	result148 := native.Trunc(0)
	_ = result148
	result149 := native.Unlerp(0, 0, 0)
	_ = result149
	result150 := native.UnlerpClamped(0, 0, 0)
	_ = result150
}

func main() {}
