//go:build ignore

// generate reads sonolus.py's ops.py and emits ops_gen.go containing the
// Pure and SideEffects classification maps.
//
// Run with:
//
//	cd compiler/ir && go run ./generate/main.go
//
// Requires a sibling sonolus.py checkout at the path resolved below.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
)

// ops.py line format: Name = ("Name", side_effects_bool, pure_bool, control_flow_bool)
var opLine = regexp.MustCompile(`^[ \t]*(\w+)\s*=\s*\("(\w+)",\s*(True|False),\s*(True|False),\s*(True|False)\)`)

func main() {
	// Locate sonolus.py relative to this module.
	_, thisFile, _, _ := runtime.Caller(0)
	// Walk up from compiler/ir/generate/main.go → sonolus.py/sonolus/backend/ops.py
	root := filepath.Join(filepath.Dir(thisFile), "..", "..", "..", "..", "sonolus.py", "sonolus", "backend", "ops.py")
	root, err := filepath.Abs(root)
	if err != nil {
		fmt.Fprintf(os.Stderr, "resolving path: %v\n", err)
		os.Exit(1)
	}

	f, err := os.Open(root)
	if err != nil {
		fmt.Fprintf(os.Stderr, "cannot open %s: %v\n", root, err)
		os.Exit(1)
	}
	defer f.Close()

	var sideEffects, pure []string
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		m := opLine.FindStringSubmatch(sc.Text())
		if m == nil {
			continue
		}
		name := m[2]
		se := m[3] == "True"
		pu := m[4] == "True"
		if se {
			sideEffects = append(sideEffects, fmt.Sprintf("%q: true", name))
		}
		if pu {
			pure = append(pure, fmt.Sprintf("%q: true", name))
		}
	}
	if err := sc.Err(); err != nil {
		fmt.Fprintf(os.Stderr, "reading: %v\n", err)
		os.Exit(1)
	}

	outPath := filepath.Join(filepath.Dir(thisFile), "..", "ops_gen.go")

	var buf bytes.Buffer
	fmt.Fprintf(&buf, `// Code generated by compiler/ir/generate; DO NOT EDIT.
// Reads sonolus.py/sonolus/backend/ops.py Op classification.

package ir

import "github.com/WindowsSov8forUs/sonolus-core-go/core/resource"

var sideEffectOps = map[resource.RuntimeFunction]bool{
	%s,
}

var pureOps = map[resource.RuntimeFunction]bool{
	%s,
}
`, strings.Join(sideEffects, ",\n\t"), strings.Join(pure, ",\n\t"))

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "gofmt: %v\n", err)
		// Write unformatted as fallback so the generator doesn't lose data.
		formatted = buf.Bytes()
	}
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "writing %s: %v\n", outPath, err)
		os.Exit(1)
	}
}
